//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public System.Guid usu_id_usuario { get; set; }
        public string usu_ds_login { get; set; }
        public string usu_ds_password { get; set; }
        public string usu_ds_email { get; set; }
        public string usu_ds_telefone { get; set; }
        public string usu_ds_cpf { get; set; }
        public string usu_ds_imagem { get; set; }
        public string usu_ds_nome { get; set; }
        public bool usu_st_ativo { get; set; }
    }
}
